/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./components/BackButton.vue')['default']
    BoxItem: typeof import('./components/BoxItem.vue')['default']
    Calendar: typeof import('./components/Calendar.vue')['default']
    CalendarDate: typeof import('./components/CalendarDate.vue')['default']
    Comments: typeof import('./components/Comments.vue')['default']
    CommentsCard: typeof import('./components/CommentsCard.vue')['default']
    CommunityHeader: typeof import('./components/CommunityHeader.vue')['default']
    CustomInput: typeof import('./components/CustomInput.vue')['default']
    LexiconBox: typeof import('./components/LexiconBox.vue')['default']
    OverviewContent: typeof import('./components/OverviewContent.vue')['default']
    PostCard: typeof import('./components/PostCard.vue')['default']
    PostHeader: typeof import('./components/PostHeader.vue')['default']
    TabBar: typeof import('./components/TabBar.vue')['default']
    UserLexiconBox: typeof import('./components/UserLexiconBox.vue')['default']
    WordBox: typeof import('./components/WordBox.vue')['default']
    WordCardContent: typeof import('./components/WordCardContent.vue')['default']
    WordCardsHeader: typeof import('./components/WordCardsHeader.vue')['default']
  }
}
